spring.devtools.remote.secret=123

spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.default_schema=study_docker
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.PostgreSQLDialect

spring.datasource.url=jdbc:postgresql://dbpostgresql:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
